### PR TITLE
Added pgSQL

### PR DESCRIPTION
**Pull request by salvoravida**
This Pull Request adds support for pgSQL!

Relative discussion:

https://github.com/DTStack/monaco-sql-languages/issues/15

Mandatory PR 
https://github.com/DTStack/dt-sql-parser/pull/59

Lmk!

### CODE REVIEW

**Comment by salvoravida** [comment]
You can try a pre-built version here @salvoravida/monaco-sql-languages@0.9.9

 https://www.npmjs.com/package/@salvoravida/monaco-sql-languages?activeTab=versions

lmk

**Comment by wewoor** [comment]
> You can try a pre-built version here @salvoravida/monaco-sql-languages@0.9.9
> 
> https://www.npmjs.com/package/@salvoravida/monaco-sql-languages?activeTab=versions
> 
> lmk

In the `web` folder, there has a  preview  integration, you can add it~

**Comment by salvoravida** [comment]
> > You can try a pre-built version here @salvoravida/monaco-sql-languages@0.9.9
> > https://www.npmjs.com/package/@salvoravida/monaco-sql-languages?activeTab=versions
> > lmk
> 
> In the `web` folder, there has a preview integration, you can add it~

done it uses the last parser @salvoravida/monaco-sql-languages@0.9.10

**Comment by salvoravida** [comment]
@wewoor Waiting for the new npm release of "dt-sql-parser", so I can remove my scoped build from this PR

"dependencies": {
		- "dt-sql-parser": "^4.0.0-beta.2.2"
		+ "dt-sql-parser": "npm:@salvoravida/dt-sql-parser@4.0.0-beta.2.10"
	}

lmk

**Comment by salvoravida** [comment]
@wewoor you can test here https://salvoravida.github.io/monaco-sql-languages/

**Comment by salvoravida** [comment]
@wewoor updated to beta3

**Review by wewoor — APPROVED** [review]
LGTM

**Pull request merged**
